RestClients:
  #Twitter API v2 available endpoints
  Twitter API (Twitter API v2):
    UUID: 0b74edb8-5459-4ccc-aac7-505531e06398
    Url: ${ivy.var.Twitter-connector.Url}
    Icon: res:/webContent/icons/twitter.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - com.twitter.auth.OAuth2Feature
    Properties:
      API.key: ${ivy.var.Twitter-connector.Key}
      API.secretKey: ${ivy.var.Twitter-connector.SecretKey}
      AUTH.baseUri: https://api.twitter.com/oauth2
