Variables:

  Twitter-connector:
    
    # Url to twitter connector
    Url: "https://api.twitter.com"

    # Key to connect to the Twitter Account
    Key: 

    # SecretKey to connect to the Twitter Account
    SecretKey: 
