/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.Rule;
import com.twitter.api.client.RulesResponseMetadata;

import java.util.ArrayList;
import java.util.List;
/**
 * A response from adding user-specified stream filtering rules.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class AddRulesResponse implements OneOfAddOrDeleteRulesResponse {
  @JsonProperty("data")
  private List<Rule> data = new ArrayList<>();

  @JsonProperty("meta")
  private RulesResponseMetadata meta = null;

  public AddRulesResponse data(List<Rule> data) {
    this.data = data;
    return this;
  }

  public AddRulesResponse addDataItem(Rule dataItem) {
    this.data.add(dataItem);
    return this;
  }

   /**
   * All user-specified stream filtering rules that were created.
   * @return data
  **/
  public List<Rule> getData() {
    return data;
  }

  public void setData(List<Rule> data) {
    this.data = data;
  }

  public AddRulesResponse meta(RulesResponseMetadata meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  public RulesResponseMetadata getMeta() {
    return meta;
  }

  public void setMeta(RulesResponseMetadata meta) {
    this.meta = meta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddRulesResponse addRulesResponse = (AddRulesResponse) o;
    return Objects.equals(this.data, addRulesResponse.data) &&
        Objects.equals(this.meta, addRulesResponse.meta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, meta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddRulesResponse {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
