/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.RuleNoId;

import java.util.ArrayList;
import java.util.List;
/**
 * A request to add a user-specified stream filtering rule.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class AddRulesRequest implements OneOfAddOrDeleteRulesRequest {
  @JsonProperty("add")
  private List<RuleNoId> add = new ArrayList<>();

  public AddRulesRequest add(List<RuleNoId> add) {
    this.add = add;
    return this;
  }

  public AddRulesRequest addAddItem(RuleNoId addItem) {
    this.add.add(addItem);
    return this;
  }

   /**
   * Get add
   * @return add
  **/
  public List<RuleNoId> getAdd() {
    return add;
  }

  public void setAdd(List<RuleNoId> add) {
    this.add = add;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddRulesRequest addRulesRequest = (AddRulesRequest) o;
    return Objects.equals(this.add, addRulesRequest.add);
  }

  @Override
  public int hashCode() {
    return Objects.hash(add);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddRulesRequest {\n");
    
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
