/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.ComplianceJobType;

/**
 * A request to create a new batch compliance job.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class ComplianceJobsBody {
  @JsonProperty("type")
  private ComplianceJobType type = null;

  @JsonProperty("resumable")
  private Boolean resumable = null;

  @JsonProperty("name")
  private String name = null;

  public ComplianceJobsBody type(ComplianceJobType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public ComplianceJobType getType() {
    return type;
  }

  public void setType(ComplianceJobType type) {
    this.type = type;
  }

  public ComplianceJobsBody resumable(Boolean resumable) {
    this.resumable = resumable;
    return this;
  }

   /**
   * If true, this endpoint will return a pre-signed URL with resumable uploads enabled
   * @return resumable
  **/
  public Boolean isResumable() {
    return resumable;
  }

  public void setResumable(Boolean resumable) {
    this.resumable = resumable;
  }

  public ComplianceJobsBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplianceJobsBody complianceJobsBody = (ComplianceJobsBody) o;
    return Objects.equals(this.type, complianceJobsBody.type) &&
        Objects.equals(this.resumable, complianceJobsBody.resumable) &&
        Objects.equals(this.name, complianceJobsBody.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, resumable, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplianceJobsBody {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    resumable: ").append(toIndentedString(resumable)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
