/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.ComplianceJobStatus;
import com.twitter.api.client.ComplianceJobType;

import java.time.OffsetDateTime;
/**
 * ComplianceJob
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class ComplianceJob {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("type")
  private ComplianceJobType type = null;

  @JsonProperty("created_at")
  private OffsetDateTime createdAt = null;

  @JsonProperty("upload_url")
  private String uploadUrl = null;

  @JsonProperty("upload_expires_at")
  private OffsetDateTime uploadExpiresAt = null;

  @JsonProperty("download_url")
  private String downloadUrl = null;

  @JsonProperty("download_expires_at")
  private OffsetDateTime downloadExpiresAt = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("status")
  private ComplianceJobStatus status = null;

  public ComplianceJob id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ComplianceJob type(ComplianceJobType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public ComplianceJobType getType() {
    return type;
  }

  public void setType(ComplianceJobType type) {
    this.type = type;
  }

  public ComplianceJob createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ComplianceJob uploadUrl(String uploadUrl) {
    this.uploadUrl = uploadUrl;
    return this;
  }

   /**
   * Get uploadUrl
   * @return uploadUrl
  **/
  public String getUploadUrl() {
    return uploadUrl;
  }

  public void setUploadUrl(String uploadUrl) {
    this.uploadUrl = uploadUrl;
  }

  public ComplianceJob uploadExpiresAt(OffsetDateTime uploadExpiresAt) {
    this.uploadExpiresAt = uploadExpiresAt;
    return this;
  }

   /**
   * Get uploadExpiresAt
   * @return uploadExpiresAt
  **/
  public OffsetDateTime getUploadExpiresAt() {
    return uploadExpiresAt;
  }

  public void setUploadExpiresAt(OffsetDateTime uploadExpiresAt) {
    this.uploadExpiresAt = uploadExpiresAt;
  }

  public ComplianceJob downloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
    return this;
  }

   /**
   * Get downloadUrl
   * @return downloadUrl
  **/
  public String getDownloadUrl() {
    return downloadUrl;
  }

  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }

  public ComplianceJob downloadExpiresAt(OffsetDateTime downloadExpiresAt) {
    this.downloadExpiresAt = downloadExpiresAt;
    return this;
  }

   /**
   * Get downloadExpiresAt
   * @return downloadExpiresAt
  **/
  public OffsetDateTime getDownloadExpiresAt() {
    return downloadExpiresAt;
  }

  public void setDownloadExpiresAt(OffsetDateTime downloadExpiresAt) {
    this.downloadExpiresAt = downloadExpiresAt;
  }

  public ComplianceJob name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComplianceJob status(ComplianceJobStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public ComplianceJobStatus getStatus() {
    return status;
  }

  public void setStatus(ComplianceJobStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplianceJob complianceJob = (ComplianceJob) o;
    return Objects.equals(this.id, complianceJob.id) &&
        Objects.equals(this.type, complianceJob.type) &&
        Objects.equals(this.createdAt, complianceJob.createdAt) &&
        Objects.equals(this.uploadUrl, complianceJob.uploadUrl) &&
        Objects.equals(this.uploadExpiresAt, complianceJob.uploadExpiresAt) &&
        Objects.equals(this.downloadUrl, complianceJob.downloadUrl) &&
        Objects.equals(this.downloadExpiresAt, complianceJob.downloadExpiresAt) &&
        Objects.equals(this.name, complianceJob.name) &&
        Objects.equals(this.status, complianceJob.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, createdAt, uploadUrl, uploadExpiresAt, downloadUrl, downloadExpiresAt, name, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplianceJob {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    uploadUrl: ").append(toIndentedString(uploadUrl)).append("\n");
    sb.append("    uploadExpiresAt: ").append(toIndentedString(uploadExpiresAt)).append("\n");
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("    downloadExpiresAt: ").append(toIndentedString(downloadExpiresAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
