/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.ContextAnnotationDomainFields;
import com.twitter.api.client.ContextAnnotationEntityFields;

/**
 * Annotation inferred from the tweet text.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class ContextAnnotation {
  @JsonProperty("domain")
  private ContextAnnotationDomainFields domain = null;

  @JsonProperty("entity")
  private ContextAnnotationEntityFields entity = null;

  public ContextAnnotation domain(ContextAnnotationDomainFields domain) {
    this.domain = domain;
    return this;
  }

   /**
   * Get domain
   * @return domain
  **/
  public ContextAnnotationDomainFields getDomain() {
    return domain;
  }

  public void setDomain(ContextAnnotationDomainFields domain) {
    this.domain = domain;
  }

  public ContextAnnotation entity(ContextAnnotationEntityFields entity) {
    this.entity = entity;
    return this;
  }

   /**
   * Get entity
   * @return entity
  **/
  public ContextAnnotationEntityFields getEntity() {
    return entity;
  }

  public void setEntity(ContextAnnotationEntityFields entity) {
    this.entity = entity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContextAnnotation contextAnnotation = (ContextAnnotation) o;
    return Objects.equals(this.domain, contextAnnotation.domain) &&
        Objects.equals(this.entity, contextAnnotation.entity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, entity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContextAnnotation {\n");
    
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
