/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.CashtagEntity;
import com.twitter.api.client.HashtagEntity;
import com.twitter.api.client.MentionEntity;
import com.twitter.api.client.UrlEntity;

import java.util.ArrayList;
import java.util.List;
/**
 * FullTextEntities
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class FullTextEntities {
  @JsonProperty("urls")
  private List<UrlEntity> urls = null;

  @JsonProperty("hashtags")
  private List<HashtagEntity> hashtags = null;

  @JsonProperty("mentions")
  private List<MentionEntity> mentions = null;

  @JsonProperty("cashtags")
  private List<CashtagEntity> cashtags = null;

  public FullTextEntities urls(List<UrlEntity> urls) {
    this.urls = urls;
    return this;
  }

  public FullTextEntities addUrlsItem(UrlEntity urlsItem) {
    if (this.urls == null) {
      this.urls = new ArrayList<>();
    }
    this.urls.add(urlsItem);
    return this;
  }

   /**
   * Get urls
   * @return urls
  **/
  public List<UrlEntity> getUrls() {
    return urls;
  }

  public void setUrls(List<UrlEntity> urls) {
    this.urls = urls;
  }

  public FullTextEntities hashtags(List<HashtagEntity> hashtags) {
    this.hashtags = hashtags;
    return this;
  }

  public FullTextEntities addHashtagsItem(HashtagEntity hashtagsItem) {
    if (this.hashtags == null) {
      this.hashtags = new ArrayList<>();
    }
    this.hashtags.add(hashtagsItem);
    return this;
  }

   /**
   * Get hashtags
   * @return hashtags
  **/
  public List<HashtagEntity> getHashtags() {
    return hashtags;
  }

  public void setHashtags(List<HashtagEntity> hashtags) {
    this.hashtags = hashtags;
  }

  public FullTextEntities mentions(List<MentionEntity> mentions) {
    this.mentions = mentions;
    return this;
  }

  public FullTextEntities addMentionsItem(MentionEntity mentionsItem) {
    if (this.mentions == null) {
      this.mentions = new ArrayList<>();
    }
    this.mentions.add(mentionsItem);
    return this;
  }

   /**
   * Get mentions
   * @return mentions
  **/
  public List<MentionEntity> getMentions() {
    return mentions;
  }

  public void setMentions(List<MentionEntity> mentions) {
    this.mentions = mentions;
  }

  public FullTextEntities cashtags(List<CashtagEntity> cashtags) {
    this.cashtags = cashtags;
    return this;
  }

  public FullTextEntities addCashtagsItem(CashtagEntity cashtagsItem) {
    if (this.cashtags == null) {
      this.cashtags = new ArrayList<>();
    }
    this.cashtags.add(cashtagsItem);
    return this;
  }

   /**
   * Get cashtags
   * @return cashtags
  **/
  public List<CashtagEntity> getCashtags() {
    return cashtags;
  }

  public void setCashtags(List<CashtagEntity> cashtags) {
    this.cashtags = cashtags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullTextEntities fullTextEntities = (FullTextEntities) o;
    return Objects.equals(this.urls, fullTextEntities.urls) &&
        Objects.equals(this.hashtags, fullTextEntities.hashtags) &&
        Objects.equals(this.mentions, fullTextEntities.mentions) &&
        Objects.equals(this.cashtags, fullTextEntities.cashtags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(urls, hashtags, mentions, cashtags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullTextEntities {\n");
    
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("    hashtags: ").append(toIndentedString(hashtags)).append("\n");
    sb.append("    mentions: ").append(toIndentedString(mentions)).append("\n");
    sb.append("    cashtags: ").append(toIndentedString(cashtags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
