/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GenericMultipleUsersLookupResponseMeta
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class GenericMultipleUsersLookupResponseMeta {
  @JsonProperty("previous_token")
  private String previousToken = null;

  @JsonProperty("next_token")
  private String nextToken = null;

  @JsonProperty("result_count")
  private Integer resultCount = null;

  public GenericMultipleUsersLookupResponseMeta previousToken(String previousToken) {
    this.previousToken = previousToken;
    return this;
  }

   /**
   * The previous token
   * @return previousToken
  **/
  public String getPreviousToken() {
    return previousToken;
  }

  public void setPreviousToken(String previousToken) {
    this.previousToken = previousToken;
  }

  public GenericMultipleUsersLookupResponseMeta nextToken(String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

   /**
   * The next token
   * @return nextToken
  **/
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(String nextToken) {
    this.nextToken = nextToken;
  }

  public GenericMultipleUsersLookupResponseMeta resultCount(Integer resultCount) {
    this.resultCount = resultCount;
    return this;
  }

   /**
   * The number of user results returned in this response
   * @return resultCount
  **/
  public Integer getResultCount() {
    return resultCount;
  }

  public void setResultCount(Integer resultCount) {
    this.resultCount = resultCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericMultipleUsersLookupResponseMeta genericMultipleUsersLookupResponseMeta = (GenericMultipleUsersLookupResponseMeta) o;
    return Objects.equals(this.previousToken, genericMultipleUsersLookupResponseMeta.previousToken) &&
        Objects.equals(this.nextToken, genericMultipleUsersLookupResponseMeta.nextToken) &&
        Objects.equals(this.resultCount, genericMultipleUsersLookupResponseMeta.resultCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(previousToken, nextToken, resultCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericMultipleUsersLookupResponseMeta {\n");
    
    sb.append("    previousToken: ").append(toIndentedString(previousToken)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    resultCount: ").append(toIndentedString(resultCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
