/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GenericTweetsTimelineResponseMeta
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class GenericTweetsTimelineResponseMeta {
  @JsonProperty("newest_id")
  private String newestId = null;

  @JsonProperty("oldest_id")
  private String oldestId = null;

  @JsonProperty("previous_token")
  private String previousToken = null;

  @JsonProperty("next_token")
  private String nextToken = null;

  @JsonProperty("result_count")
  private Integer resultCount = null;

  public GenericTweetsTimelineResponseMeta newestId(String newestId) {
    this.newestId = newestId;
    return this;
  }

   /**
   * Get newestId
   * @return newestId
  **/
  public String getNewestId() {
    return newestId;
  }

  public void setNewestId(String newestId) {
    this.newestId = newestId;
  }

  public GenericTweetsTimelineResponseMeta oldestId(String oldestId) {
    this.oldestId = oldestId;
    return this;
  }

   /**
   * Get oldestId
   * @return oldestId
  **/
  public String getOldestId() {
    return oldestId;
  }

  public void setOldestId(String oldestId) {
    this.oldestId = oldestId;
  }

  public GenericTweetsTimelineResponseMeta previousToken(String previousToken) {
    this.previousToken = previousToken;
    return this;
  }

   /**
   * The previous token
   * @return previousToken
  **/
  public String getPreviousToken() {
    return previousToken;
  }

  public void setPreviousToken(String previousToken) {
    this.previousToken = previousToken;
  }

  public GenericTweetsTimelineResponseMeta nextToken(String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

   /**
   * The next token
   * @return nextToken
  **/
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(String nextToken) {
    this.nextToken = nextToken;
  }

  public GenericTweetsTimelineResponseMeta resultCount(Integer resultCount) {
    this.resultCount = resultCount;
    return this;
  }

   /**
   * Number of Tweets in result set
   * @return resultCount
  **/
  public Integer getResultCount() {
    return resultCount;
  }

  public void setResultCount(Integer resultCount) {
    this.resultCount = resultCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericTweetsTimelineResponseMeta genericTweetsTimelineResponseMeta = (GenericTweetsTimelineResponseMeta) o;
    return Objects.equals(this.newestId, genericTweetsTimelineResponseMeta.newestId) &&
        Objects.equals(this.oldestId, genericTweetsTimelineResponseMeta.oldestId) &&
        Objects.equals(this.previousToken, genericTweetsTimelineResponseMeta.previousToken) &&
        Objects.equals(this.nextToken, genericTweetsTimelineResponseMeta.nextToken) &&
        Objects.equals(this.resultCount, genericTweetsTimelineResponseMeta.resultCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newestId, oldestId, previousToken, nextToken, resultCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericTweetsTimelineResponseMeta {\n");
    
    sb.append("    newestId: ").append(toIndentedString(newestId)).append("\n");
    sb.append("    oldestId: ").append(toIndentedString(oldestId)).append("\n");
    sb.append("    previousToken: ").append(toIndentedString(previousToken)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    resultCount: ").append(toIndentedString(resultCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
