/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Tweet information of the Tweet being replied to.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class Model2tweetsReply {
  @JsonProperty("in_reply_to_tweet_id")
  private String inReplyToTweetId = null;

  @JsonProperty("exclude_reply_user_ids")
  private List<String> excludeReplyUserIds = null;

  public Model2tweetsReply inReplyToTweetId(String inReplyToTweetId) {
    this.inReplyToTweetId = inReplyToTweetId;
    return this;
  }

   /**
   * Get inReplyToTweetId
   * @return inReplyToTweetId
  **/
  public String getInReplyToTweetId() {
    return inReplyToTweetId;
  }

  public void setInReplyToTweetId(String inReplyToTweetId) {
    this.inReplyToTweetId = inReplyToTweetId;
  }

  public Model2tweetsReply excludeReplyUserIds(List<String> excludeReplyUserIds) {
    this.excludeReplyUserIds = excludeReplyUserIds;
    return this;
  }

  public Model2tweetsReply addExcludeReplyUserIdsItem(String excludeReplyUserIdsItem) {
    if (this.excludeReplyUserIds == null) {
      this.excludeReplyUserIds = new ArrayList<>();
    }
    this.excludeReplyUserIds.add(excludeReplyUserIdsItem);
    return this;
  }

   /**
   * A list of User Ids to be excluded from the reply Tweet.
   * @return excludeReplyUserIds
  **/
  public List<String> getExcludeReplyUserIds() {
    return excludeReplyUserIds;
  }

  public void setExcludeReplyUserIds(List<String> excludeReplyUserIds) {
    this.excludeReplyUserIds = excludeReplyUserIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model2tweetsReply _2tweetsReply = (Model2tweetsReply) o;
    return Objects.equals(this.inReplyToTweetId, _2tweetsReply.inReplyToTweetId) &&
        Objects.equals(this.excludeReplyUserIds, _2tweetsReply.excludeReplyUserIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inReplyToTweetId, excludeReplyUserIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Model2tweetsReply {\n");
    
    sb.append("    inReplyToTweetId: ").append(toIndentedString(inReplyToTweetId)).append("\n");
    sb.append("    excludeReplyUserIds: ").append(toIndentedString(excludeReplyUserIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
