/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Media information being attached to created Tweet. This is mutually exclusive from Quote Tweet Id and Poll.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class Model2tweetsMedia {
  @JsonProperty("media_ids")
  private List<String> mediaIds = null;

  @JsonProperty("tagged_user_ids")
  private List<String> taggedUserIds = null;

  public Model2tweetsMedia mediaIds(List<String> mediaIds) {
    this.mediaIds = mediaIds;
    return this;
  }

  public Model2tweetsMedia addMediaIdsItem(String mediaIdsItem) {
    if (this.mediaIds == null) {
      this.mediaIds = new ArrayList<>();
    }
    this.mediaIds.add(mediaIdsItem);
    return this;
  }

   /**
   * A list of Media Ids to be attached to a created Tweet.
   * @return mediaIds
  **/
  public List<String> getMediaIds() {
    return mediaIds;
  }

  public void setMediaIds(List<String> mediaIds) {
    this.mediaIds = mediaIds;
  }

  public Model2tweetsMedia taggedUserIds(List<String> taggedUserIds) {
    this.taggedUserIds = taggedUserIds;
    return this;
  }

  public Model2tweetsMedia addTaggedUserIdsItem(String taggedUserIdsItem) {
    if (this.taggedUserIds == null) {
      this.taggedUserIds = new ArrayList<>();
    }
    this.taggedUserIds.add(taggedUserIdsItem);
    return this;
  }

   /**
   * A list of User Ids to be tagged in the media for created Tweet.
   * @return taggedUserIds
  **/
  public List<String> getTaggedUserIds() {
    return taggedUserIds;
  }

  public void setTaggedUserIds(List<String> taggedUserIds) {
    this.taggedUserIds = taggedUserIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model2tweetsMedia _2tweetsMedia = (Model2tweetsMedia) o;
    return Objects.equals(this.mediaIds, _2tweetsMedia.mediaIds) &&
        Objects.equals(this.taggedUserIds, _2tweetsMedia.taggedUserIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mediaIds, taggedUserIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Model2tweetsMedia {\n");
    
    sb.append("    mediaIds: ").append(toIndentedString(mediaIds)).append("\n");
    sb.append("    taggedUserIds: ").append(toIndentedString(taggedUserIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
