/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.Model2tweetsGeo;
import com.twitter.api.client.Model2tweetsMedia;
import com.twitter.api.client.Model2tweetsPoll;
import com.twitter.api.client.Model2tweetsReply;

/**
 * Model2TweetsBody
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class Model2TweetsBody {
  @JsonProperty("text")
  private String text = null;

  @JsonProperty("direct_message_deep_link")
  private String directMessageDeepLink = null;

  @JsonProperty("quote_tweet_id")
  private String quoteTweetId = null;

  @JsonProperty("for_super_followers_only")
  private Boolean forSuperFollowersOnly = null;

  @JsonProperty("reply")
  private Model2tweetsReply reply = null;

  @JsonProperty("media")
  private Model2tweetsMedia media = null;

  @JsonProperty("poll")
  private Model2tweetsPoll poll = null;

  /**
   * Settings to indicate who can reply to the Tweet.
   */
  public enum ReplySettingsEnum {
    FOLLOWING("following"),
    MENTIONEDUSERS("mentionedUsers");

    private String value;

    ReplySettingsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ReplySettingsEnum fromValue(String text) {
      for (ReplySettingsEnum b : ReplySettingsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("reply_settings")
  private ReplySettingsEnum replySettings = null;

  @JsonProperty("geo")
  private Model2tweetsGeo geo = null;

  public Model2TweetsBody text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public Model2TweetsBody directMessageDeepLink(String directMessageDeepLink) {
    this.directMessageDeepLink = directMessageDeepLink;
    return this;
  }

   /**
   * Link to take the conversation from the public timeline to a private Direct Message.
   * @return directMessageDeepLink
  **/
  public String getDirectMessageDeepLink() {
    return directMessageDeepLink;
  }

  public void setDirectMessageDeepLink(String directMessageDeepLink) {
    this.directMessageDeepLink = directMessageDeepLink;
  }

  public Model2TweetsBody quoteTweetId(String quoteTweetId) {
    this.quoteTweetId = quoteTweetId;
    return this;
  }

   /**
   * Get quoteTweetId
   * @return quoteTweetId
  **/
  public String getQuoteTweetId() {
    return quoteTweetId;
  }

  public void setQuoteTweetId(String quoteTweetId) {
    this.quoteTweetId = quoteTweetId;
  }

  public Model2TweetsBody forSuperFollowersOnly(Boolean forSuperFollowersOnly) {
    this.forSuperFollowersOnly = forSuperFollowersOnly;
    return this;
  }

   /**
   * Exclusive Tweet for super followers.
   * @return forSuperFollowersOnly
  **/
  public Boolean isForSuperFollowersOnly() {
    return forSuperFollowersOnly;
  }

  public void setForSuperFollowersOnly(Boolean forSuperFollowersOnly) {
    this.forSuperFollowersOnly = forSuperFollowersOnly;
  }

  public Model2TweetsBody reply(Model2tweetsReply reply) {
    this.reply = reply;
    return this;
  }

   /**
   * Get reply
   * @return reply
  **/
  public Model2tweetsReply getReply() {
    return reply;
  }

  public void setReply(Model2tweetsReply reply) {
    this.reply = reply;
  }

  public Model2TweetsBody media(Model2tweetsMedia media) {
    this.media = media;
    return this;
  }

   /**
   * Get media
   * @return media
  **/
  public Model2tweetsMedia getMedia() {
    return media;
  }

  public void setMedia(Model2tweetsMedia media) {
    this.media = media;
  }

  public Model2TweetsBody poll(Model2tweetsPoll poll) {
    this.poll = poll;
    return this;
  }

   /**
   * Get poll
   * @return poll
  **/
  public Model2tweetsPoll getPoll() {
    return poll;
  }

  public void setPoll(Model2tweetsPoll poll) {
    this.poll = poll;
  }

  public Model2TweetsBody replySettings(ReplySettingsEnum replySettings) {
    this.replySettings = replySettings;
    return this;
  }

   /**
   * Settings to indicate who can reply to the Tweet.
   * @return replySettings
  **/
  public ReplySettingsEnum getReplySettings() {
    return replySettings;
  }

  public void setReplySettings(ReplySettingsEnum replySettings) {
    this.replySettings = replySettings;
  }

  public Model2TweetsBody geo(Model2tweetsGeo geo) {
    this.geo = geo;
    return this;
  }

   /**
   * Get geo
   * @return geo
  **/
  public Model2tweetsGeo getGeo() {
    return geo;
  }

  public void setGeo(Model2tweetsGeo geo) {
    this.geo = geo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model2TweetsBody _2TweetsBody = (Model2TweetsBody) o;
    return Objects.equals(this.text, _2TweetsBody.text) &&
        Objects.equals(this.directMessageDeepLink, _2TweetsBody.directMessageDeepLink) &&
        Objects.equals(this.quoteTweetId, _2TweetsBody.quoteTweetId) &&
        Objects.equals(this.forSuperFollowersOnly, _2TweetsBody.forSuperFollowersOnly) &&
        Objects.equals(this.reply, _2TweetsBody.reply) &&
        Objects.equals(this.media, _2TweetsBody.media) &&
        Objects.equals(this.poll, _2TweetsBody.poll) &&
        Objects.equals(this.replySettings, _2TweetsBody.replySettings) &&
        Objects.equals(this.geo, _2TweetsBody.geo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, directMessageDeepLink, quoteTweetId, forSuperFollowersOnly, reply, media, poll, replySettings, geo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Model2TweetsBody {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    directMessageDeepLink: ").append(toIndentedString(directMessageDeepLink)).append("\n");
    sb.append("    quoteTweetId: ").append(toIndentedString(quoteTweetId)).append("\n");
    sb.append("    forSuperFollowersOnly: ").append(toIndentedString(forSuperFollowersOnly)).append("\n");
    sb.append("    reply: ").append(toIndentedString(reply)).append("\n");
    sb.append("    media: ").append(toIndentedString(media)).append("\n");
    sb.append("    poll: ").append(toIndentedString(poll)).append("\n");
    sb.append("    replySettings: ").append(toIndentedString(replySettings)).append("\n");
    sb.append("    geo: ").append(toIndentedString(geo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
