/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.PollOption;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * Represent a Poll attached to a Tweet
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class Poll {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("options")
  private List<PollOption> options = new ArrayList<>();

  /**
   * Gets or Sets votingStatus
   */
  public enum VotingStatusEnum {
    OPEN("open"),
    CLOSED("closed");

    private String value;

    VotingStatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static VotingStatusEnum fromValue(String text) {
      for (VotingStatusEnum b : VotingStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("voting_status")
  private VotingStatusEnum votingStatus = null;

  @JsonProperty("end_datetime")
  private OffsetDateTime endDatetime = null;

  @JsonProperty("duration_minutes")
  private Integer durationMinutes = null;

  public Poll id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Poll options(List<PollOption> options) {
    this.options = options;
    return this;
  }

  public Poll addOptionsItem(PollOption optionsItem) {
    this.options.add(optionsItem);
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  public List<PollOption> getOptions() {
    return options;
  }

  public void setOptions(List<PollOption> options) {
    this.options = options;
  }

  public Poll votingStatus(VotingStatusEnum votingStatus) {
    this.votingStatus = votingStatus;
    return this;
  }

   /**
   * Get votingStatus
   * @return votingStatus
  **/
  public VotingStatusEnum getVotingStatus() {
    return votingStatus;
  }

  public void setVotingStatus(VotingStatusEnum votingStatus) {
    this.votingStatus = votingStatus;
  }

  public Poll endDatetime(OffsetDateTime endDatetime) {
    this.endDatetime = endDatetime;
    return this;
  }

   /**
   * Get endDatetime
   * @return endDatetime
  **/
  public OffsetDateTime getEndDatetime() {
    return endDatetime;
  }

  public void setEndDatetime(OffsetDateTime endDatetime) {
    this.endDatetime = endDatetime;
  }

  public Poll durationMinutes(Integer durationMinutes) {
    this.durationMinutes = durationMinutes;
    return this;
  }

   /**
   * Get durationMinutes
   * @return durationMinutes
  **/
  public Integer getDurationMinutes() {
    return durationMinutes;
  }

  public void setDurationMinutes(Integer durationMinutes) {
    this.durationMinutes = durationMinutes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Poll poll = (Poll) o;
    return Objects.equals(this.id, poll.id) &&
        Objects.equals(this.options, poll.options) &&
        Objects.equals(this.votingStatus, poll.votingStatus) &&
        Objects.equals(this.endDatetime, poll.endDatetime) &&
        Objects.equals(this.durationMinutes, poll.durationMinutes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, options, votingStatus, endDatetime, durationMinutes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Poll {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    votingStatus: ").append(toIndentedString(votingStatus)).append("\n");
    sb.append("    endDatetime: ").append(toIndentedString(endDatetime)).append("\n");
    sb.append("    durationMinutes: ").append(toIndentedString(durationMinutes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
