/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Shows who can reply a Tweet. Fields returned are everyone, mentioned_users, and following.
 */
public enum ReplySettings {
  EVERYONE("everyone"),
  MENTIONEDUSERS("mentionedUsers"),
  FOLLOWING("following"),
  OTHER("other");

  private String value;

  ReplySettings(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ReplySettings fromValue(String text) {
    for (ReplySettings b : ReplySettings.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
