/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.SpaceTopics;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * Space
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class Space {
  @JsonProperty("id")
  private String id = null;

  /**
   * The current state of the space.
   */
  public enum StateEnum {
    LIVE("live"),
    SCHEDULED("scheduled"),
    ENDED("ended");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("state")
  private StateEnum state = null;

  @JsonProperty("started_at")
  private OffsetDateTime startedAt = null;

  @JsonProperty("is_ticketed")
  private Boolean isTicketed = null;

  @JsonProperty("participant_count")
  private Integer participantCount = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("host_ids")
  private List<String> hostIds = null;

  @JsonProperty("updated_at")
  private OffsetDateTime updatedAt = null;

  @JsonProperty("created_at")
  private OffsetDateTime createdAt = null;

  @JsonProperty("creator_id")
  private String creatorId = null;

  @JsonProperty("lang")
  private String lang = null;

  @JsonProperty("speaker_ids")
  private List<String> speakerIds = null;

  @JsonProperty("invited_user_ids")
  private List<String> invitedUserIds = null;

  @JsonProperty("scheduled_start")
  private OffsetDateTime scheduledStart = null;

  @JsonProperty("ended_at")
  private OffsetDateTime endedAt = null;

  @JsonProperty("topics")
  private List<SpaceTopics> topics = null;

  public Space id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Space state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * The current state of the space.
   * @return state
  **/
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public Space startedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * When the space was started as a date string
   * @return startedAt
  **/
  public OffsetDateTime getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }

  public Space isTicketed(Boolean isTicketed) {
    this.isTicketed = isTicketed;
    return this;
  }

   /**
   * Denotes if the space is a ticketed space
   * @return isTicketed
  **/
  public Boolean isIsTicketed() {
    return isTicketed;
  }

  public void setIsTicketed(Boolean isTicketed) {
    this.isTicketed = isTicketed;
  }

  public Space participantCount(Integer participantCount) {
    this.participantCount = participantCount;
    return this;
  }

   /**
   * The number of participants in a space
   * @return participantCount
  **/
  public Integer getParticipantCount() {
    return participantCount;
  }

  public void setParticipantCount(Integer participantCount) {
    this.participantCount = participantCount;
  }

  public Space title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The title of the space
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Space hostIds(List<String> hostIds) {
    this.hostIds = hostIds;
    return this;
  }

  public Space addHostIdsItem(String hostIdsItem) {
    if (this.hostIds == null) {
      this.hostIds = new ArrayList<>();
    }
    this.hostIds.add(hostIdsItem);
    return this;
  }

   /**
   * The user ids for the hosts of the space
   * @return hostIds
  **/
  public List<String> getHostIds() {
    return hostIds;
  }

  public void setHostIds(List<String> hostIds) {
    this.hostIds = hostIds;
  }

  public Space updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * When the space was last updated
   * @return updatedAt
  **/
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Space createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Creation time of the space
   * @return createdAt
  **/
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Space creatorId(String creatorId) {
    this.creatorId = creatorId;
    return this;
  }

   /**
   * Get creatorId
   * @return creatorId
  **/
  public String getCreatorId() {
    return creatorId;
  }

  public void setCreatorId(String creatorId) {
    this.creatorId = creatorId;
  }

  public Space lang(String lang) {
    this.lang = lang;
    return this;
  }

   /**
   * The language of the space
   * @return lang
  **/
  public String getLang() {
    return lang;
  }

  public void setLang(String lang) {
    this.lang = lang;
  }

  public Space speakerIds(List<String> speakerIds) {
    this.speakerIds = speakerIds;
    return this;
  }

  public Space addSpeakerIdsItem(String speakerIdsItem) {
    if (this.speakerIds == null) {
      this.speakerIds = new ArrayList<>();
    }
    this.speakerIds.add(speakerIdsItem);
    return this;
  }

   /**
   * An array of user ids for people who were speakers in a space
   * @return speakerIds
  **/
  public List<String> getSpeakerIds() {
    return speakerIds;
  }

  public void setSpeakerIds(List<String> speakerIds) {
    this.speakerIds = speakerIds;
  }

  public Space invitedUserIds(List<String> invitedUserIds) {
    this.invitedUserIds = invitedUserIds;
    return this;
  }

  public Space addInvitedUserIdsItem(String invitedUserIdsItem) {
    if (this.invitedUserIds == null) {
      this.invitedUserIds = new ArrayList<>();
    }
    this.invitedUserIds.add(invitedUserIdsItem);
    return this;
  }

   /**
   * An array of user ids for people who were invited to a space
   * @return invitedUserIds
  **/
  public List<String> getInvitedUserIds() {
    return invitedUserIds;
  }

  public void setInvitedUserIds(List<String> invitedUserIds) {
    this.invitedUserIds = invitedUserIds;
  }

  public Space scheduledStart(OffsetDateTime scheduledStart) {
    this.scheduledStart = scheduledStart;
    return this;
  }

   /**
   * A date time stamp for when a space is scheduled to begin
   * @return scheduledStart
  **/
  public OffsetDateTime getScheduledStart() {
    return scheduledStart;
  }

  public void setScheduledStart(OffsetDateTime scheduledStart) {
    this.scheduledStart = scheduledStart;
  }

  public Space endedAt(OffsetDateTime endedAt) {
    this.endedAt = endedAt;
    return this;
  }

   /**
   * End time of the space
   * @return endedAt
  **/
  public OffsetDateTime getEndedAt() {
    return endedAt;
  }

  public void setEndedAt(OffsetDateTime endedAt) {
    this.endedAt = endedAt;
  }

  public Space topics(List<SpaceTopics> topics) {
    this.topics = topics;
    return this;
  }

  public Space addTopicsItem(SpaceTopics topicsItem) {
    if (this.topics == null) {
      this.topics = new ArrayList<>();
    }
    this.topics.add(topicsItem);
    return this;
  }

   /**
   * The topics of a space, as selected by its creator
   * @return topics
  **/
  public List<SpaceTopics> getTopics() {
    return topics;
  }

  public void setTopics(List<SpaceTopics> topics) {
    this.topics = topics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Space space = (Space) o;
    return Objects.equals(this.id, space.id) &&
        Objects.equals(this.state, space.state) &&
        Objects.equals(this.startedAt, space.startedAt) &&
        Objects.equals(this.isTicketed, space.isTicketed) &&
        Objects.equals(this.participantCount, space.participantCount) &&
        Objects.equals(this.title, space.title) &&
        Objects.equals(this.hostIds, space.hostIds) &&
        Objects.equals(this.updatedAt, space.updatedAt) &&
        Objects.equals(this.createdAt, space.createdAt) &&
        Objects.equals(this.creatorId, space.creatorId) &&
        Objects.equals(this.lang, space.lang) &&
        Objects.equals(this.speakerIds, space.speakerIds) &&
        Objects.equals(this.invitedUserIds, space.invitedUserIds) &&
        Objects.equals(this.scheduledStart, space.scheduledStart) &&
        Objects.equals(this.endedAt, space.endedAt) &&
        Objects.equals(this.topics, space.topics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, state, startedAt, isTicketed, participantCount, title, hostIds, updatedAt, createdAt, creatorId, lang, speakerIds, invitedUserIds, scheduledStart, endedAt, topics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Space {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    isTicketed: ").append(toIndentedString(isTicketed)).append("\n");
    sb.append("    participantCount: ").append(toIndentedString(participantCount)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    hostIds: ").append(toIndentedString(hostIds)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("    speakerIds: ").append(toIndentedString(speakerIds)).append("\n");
    sb.append("    invitedUserIds: ").append(toIndentedString(invitedUserIds)).append("\n");
    sb.append("    scheduledStart: ").append(toIndentedString(scheduledStart)).append("\n");
    sb.append("    endedAt: ").append(toIndentedString(endedAt)).append("\n");
    sb.append("    topics: ").append(toIndentedString(topics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
