/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Nonpublic engagement metrics for the Tweet at the time of the request.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class TweetNonPublicMetrics {
  @JsonProperty("impression_count")
  private Integer impressionCount = null;

  public TweetNonPublicMetrics impressionCount(Integer impressionCount) {
    this.impressionCount = impressionCount;
    return this;
  }

   /**
   * Number of times this Tweet has been viewed.
   * @return impressionCount
  **/
  public Integer getImpressionCount() {
    return impressionCount;
  }

  public void setImpressionCount(Integer impressionCount) {
    this.impressionCount = impressionCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TweetNonPublicMetrics tweetNonPublicMetrics = (TweetNonPublicMetrics) o;
    return Objects.equals(this.impressionCount, tweetNonPublicMetrics.impressionCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(impressionCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TweetNonPublicMetrics {\n");
    
    sb.append("    impressionCount: ").append(toIndentedString(impressionCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
