/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * TweetCountsResponseMeta
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class TweetCountsResponseMeta {
  @JsonProperty("next_token")
  private String nextToken = null;

  @JsonProperty("total_tweet_count")
  private Integer totalTweetCount = null;

  public TweetCountsResponseMeta nextToken(String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

   /**
   * This value is used to get the next &#x27;page&#x27; of results by providing it to the next_token parameter.
   * @return nextToken
  **/
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(String nextToken) {
    this.nextToken = nextToken;
  }

  public TweetCountsResponseMeta totalTweetCount(Integer totalTweetCount) {
    this.totalTweetCount = totalTweetCount;
    return this;
  }

   /**
   * Sum of search query count results
   * @return totalTweetCount
  **/
  public Integer getTotalTweetCount() {
    return totalTweetCount;
  }

  public void setTotalTweetCount(Integer totalTweetCount) {
    this.totalTweetCount = totalTweetCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TweetCountsResponseMeta tweetCountsResponseMeta = (TweetCountsResponseMeta) o;
    return Objects.equals(this.nextToken, tweetCountsResponseMeta.nextToken) &&
        Objects.equals(this.totalTweetCount, tweetCountsResponseMeta.totalTweetCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextToken, totalTweetCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TweetCountsResponseMeta {\n");
    
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    totalTweetCount: ").append(toIndentedString(totalTweetCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
