/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.ContextAnnotation;
import com.twitter.api.client.FullTextEntities;
import com.twitter.api.client.ReplySettings;
import com.twitter.api.client.TweetAttachments;
import com.twitter.api.client.TweetGeo;
import com.twitter.api.client.TweetNonPublicMetrics;
import com.twitter.api.client.TweetOrganicMetrics;
import com.twitter.api.client.TweetPromotedMetrics;
import com.twitter.api.client.TweetPublicMetrics;
import com.twitter.api.client.TweetReferencedTweets;
import com.twitter.api.client.TweetWithheld;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * Tweet
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class Tweet {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("created_at")
  private OffsetDateTime createdAt = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("author_id")
  private String authorId = null;

  @JsonProperty("in_reply_to_user_id")
  private String inReplyToUserId = null;

  @JsonProperty("conversation_id")
  private String conversationId = null;

  @JsonProperty("reply_settings")
  private ReplySettings replySettings = null;

  @JsonProperty("referenced_tweets")
  private List<TweetReferencedTweets> referencedTweets = null;

  @JsonProperty("attachments")
  private TweetAttachments attachments = null;

  @JsonProperty("context_annotations")
  private List<ContextAnnotation> contextAnnotations = null;

  @JsonProperty("withheld")
  private TweetWithheld withheld = null;

  @JsonProperty("geo")
  private TweetGeo geo = null;

  @JsonProperty("entities")
  private FullTextEntities entities = null;

  @JsonProperty("public_metrics")
  private TweetPublicMetrics publicMetrics = null;

  @JsonProperty("possibly_sensitive")
  private Boolean possiblySensitive = null;

  @JsonProperty("lang")
  private String lang = null;

  @JsonProperty("source")
  private String source = null;

  @JsonProperty("non_public_metrics")
  private TweetNonPublicMetrics nonPublicMetrics = null;

  @JsonProperty("promoted_metrics")
  private TweetPromotedMetrics promotedMetrics = null;

  @JsonProperty("organic_metrics")
  private TweetOrganicMetrics organicMetrics = null;

  public Tweet id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Tweet createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Creation time of the Tweet.
   * @return createdAt
  **/
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Tweet text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public Tweet authorId(String authorId) {
    this.authorId = authorId;
    return this;
  }

   /**
   * Get authorId
   * @return authorId
  **/
  public String getAuthorId() {
    return authorId;
  }

  public void setAuthorId(String authorId) {
    this.authorId = authorId;
  }

  public Tweet inReplyToUserId(String inReplyToUserId) {
    this.inReplyToUserId = inReplyToUserId;
    return this;
  }

   /**
   * Get inReplyToUserId
   * @return inReplyToUserId
  **/
  public String getInReplyToUserId() {
    return inReplyToUserId;
  }

  public void setInReplyToUserId(String inReplyToUserId) {
    this.inReplyToUserId = inReplyToUserId;
  }

  public Tweet conversationId(String conversationId) {
    this.conversationId = conversationId;
    return this;
  }

   /**
   * Get conversationId
   * @return conversationId
  **/
  public String getConversationId() {
    return conversationId;
  }

  public void setConversationId(String conversationId) {
    this.conversationId = conversationId;
  }

  public Tweet replySettings(ReplySettings replySettings) {
    this.replySettings = replySettings;
    return this;
  }

   /**
   * Get replySettings
   * @return replySettings
  **/
  public ReplySettings getReplySettings() {
    return replySettings;
  }

  public void setReplySettings(ReplySettings replySettings) {
    this.replySettings = replySettings;
  }

  public Tweet referencedTweets(List<TweetReferencedTweets> referencedTweets) {
    this.referencedTweets = referencedTweets;
    return this;
  }

  public Tweet addReferencedTweetsItem(TweetReferencedTweets referencedTweetsItem) {
    if (this.referencedTweets == null) {
      this.referencedTweets = new ArrayList<>();
    }
    this.referencedTweets.add(referencedTweetsItem);
    return this;
  }

   /**
   * A list of Tweets this Tweet refers to. For example, if the parent Tweet is a Retweet, a Quoted Tweet or a Reply, it will include the related Tweet referenced to by its parent.
   * @return referencedTweets
  **/
  public List<TweetReferencedTweets> getReferencedTweets() {
    return referencedTweets;
  }

  public void setReferencedTweets(List<TweetReferencedTweets> referencedTweets) {
    this.referencedTweets = referencedTweets;
  }

  public Tweet attachments(TweetAttachments attachments) {
    this.attachments = attachments;
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  public TweetAttachments getAttachments() {
    return attachments;
  }

  public void setAttachments(TweetAttachments attachments) {
    this.attachments = attachments;
  }

  public Tweet contextAnnotations(List<ContextAnnotation> contextAnnotations) {
    this.contextAnnotations = contextAnnotations;
    return this;
  }

  public Tweet addContextAnnotationsItem(ContextAnnotation contextAnnotationsItem) {
    if (this.contextAnnotations == null) {
      this.contextAnnotations = new ArrayList<>();
    }
    this.contextAnnotations.add(contextAnnotationsItem);
    return this;
  }

   /**
   * Get contextAnnotations
   * @return contextAnnotations
  **/
  public List<ContextAnnotation> getContextAnnotations() {
    return contextAnnotations;
  }

  public void setContextAnnotations(List<ContextAnnotation> contextAnnotations) {
    this.contextAnnotations = contextAnnotations;
  }

  public Tweet withheld(TweetWithheld withheld) {
    this.withheld = withheld;
    return this;
  }

   /**
   * Get withheld
   * @return withheld
  **/
  public TweetWithheld getWithheld() {
    return withheld;
  }

  public void setWithheld(TweetWithheld withheld) {
    this.withheld = withheld;
  }

  public Tweet geo(TweetGeo geo) {
    this.geo = geo;
    return this;
  }

   /**
   * Get geo
   * @return geo
  **/
  public TweetGeo getGeo() {
    return geo;
  }

  public void setGeo(TweetGeo geo) {
    this.geo = geo;
  }

  public Tweet entities(FullTextEntities entities) {
    this.entities = entities;
    return this;
  }

   /**
   * Get entities
   * @return entities
  **/
  public FullTextEntities getEntities() {
    return entities;
  }

  public void setEntities(FullTextEntities entities) {
    this.entities = entities;
  }

  public Tweet publicMetrics(TweetPublicMetrics publicMetrics) {
    this.publicMetrics = publicMetrics;
    return this;
  }

   /**
   * Get publicMetrics
   * @return publicMetrics
  **/
  public TweetPublicMetrics getPublicMetrics() {
    return publicMetrics;
  }

  public void setPublicMetrics(TweetPublicMetrics publicMetrics) {
    this.publicMetrics = publicMetrics;
  }

  public Tweet possiblySensitive(Boolean possiblySensitive) {
    this.possiblySensitive = possiblySensitive;
    return this;
  }

   /**
   * Indicates if this Tweet contains URLs marked as sensitive, for example content suitable for mature audiences.
   * @return possiblySensitive
  **/
  public Boolean isPossiblySensitive() {
    return possiblySensitive;
  }

  public void setPossiblySensitive(Boolean possiblySensitive) {
    this.possiblySensitive = possiblySensitive;
  }

  public Tweet lang(String lang) {
    this.lang = lang;
    return this;
  }

   /**
   * Language of the Tweet, if detected by Twitter. Returned as a BCP47 language tag.
   * @return lang
  **/
  public String getLang() {
    return lang;
  }

  public void setLang(String lang) {
    this.lang = lang;
  }

  public Tweet source(String source) {
    this.source = source;
    return this;
  }

   /**
   * The name of the app the user Tweeted from.
   * @return source
  **/
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public Tweet nonPublicMetrics(TweetNonPublicMetrics nonPublicMetrics) {
    this.nonPublicMetrics = nonPublicMetrics;
    return this;
  }

   /**
   * Get nonPublicMetrics
   * @return nonPublicMetrics
  **/
  public TweetNonPublicMetrics getNonPublicMetrics() {
    return nonPublicMetrics;
  }

  public void setNonPublicMetrics(TweetNonPublicMetrics nonPublicMetrics) {
    this.nonPublicMetrics = nonPublicMetrics;
  }

  public Tweet promotedMetrics(TweetPromotedMetrics promotedMetrics) {
    this.promotedMetrics = promotedMetrics;
    return this;
  }

   /**
   * Get promotedMetrics
   * @return promotedMetrics
  **/
  public TweetPromotedMetrics getPromotedMetrics() {
    return promotedMetrics;
  }

  public void setPromotedMetrics(TweetPromotedMetrics promotedMetrics) {
    this.promotedMetrics = promotedMetrics;
  }

  public Tweet organicMetrics(TweetOrganicMetrics organicMetrics) {
    this.organicMetrics = organicMetrics;
    return this;
  }

   /**
   * Get organicMetrics
   * @return organicMetrics
  **/
  public TweetOrganicMetrics getOrganicMetrics() {
    return organicMetrics;
  }

  public void setOrganicMetrics(TweetOrganicMetrics organicMetrics) {
    this.organicMetrics = organicMetrics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tweet tweet = (Tweet) o;
    return Objects.equals(this.id, tweet.id) &&
        Objects.equals(this.createdAt, tweet.createdAt) &&
        Objects.equals(this.text, tweet.text) &&
        Objects.equals(this.authorId, tweet.authorId) &&
        Objects.equals(this.inReplyToUserId, tweet.inReplyToUserId) &&
        Objects.equals(this.conversationId, tweet.conversationId) &&
        Objects.equals(this.replySettings, tweet.replySettings) &&
        Objects.equals(this.referencedTweets, tweet.referencedTweets) &&
        Objects.equals(this.attachments, tweet.attachments) &&
        Objects.equals(this.contextAnnotations, tweet.contextAnnotations) &&
        Objects.equals(this.withheld, tweet.withheld) &&
        Objects.equals(this.geo, tweet.geo) &&
        Objects.equals(this.entities, tweet.entities) &&
        Objects.equals(this.publicMetrics, tweet.publicMetrics) &&
        Objects.equals(this.possiblySensitive, tweet.possiblySensitive) &&
        Objects.equals(this.lang, tweet.lang) &&
        Objects.equals(this.source, tweet.source) &&
        Objects.equals(this.nonPublicMetrics, tweet.nonPublicMetrics) &&
        Objects.equals(this.promotedMetrics, tweet.promotedMetrics) &&
        Objects.equals(this.organicMetrics, tweet.organicMetrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, text, authorId, inReplyToUserId, conversationId, replySettings, referencedTweets, attachments, contextAnnotations, withheld, geo, entities, publicMetrics, possiblySensitive, lang, source, nonPublicMetrics, promotedMetrics, organicMetrics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tweet {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    authorId: ").append(toIndentedString(authorId)).append("\n");
    sb.append("    inReplyToUserId: ").append(toIndentedString(inReplyToUserId)).append("\n");
    sb.append("    conversationId: ").append(toIndentedString(conversationId)).append("\n");
    sb.append("    replySettings: ").append(toIndentedString(replySettings)).append("\n");
    sb.append("    referencedTweets: ").append(toIndentedString(referencedTweets)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    contextAnnotations: ").append(toIndentedString(contextAnnotations)).append("\n");
    sb.append("    withheld: ").append(toIndentedString(withheld)).append("\n");
    sb.append("    geo: ").append(toIndentedString(geo)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    publicMetrics: ").append(toIndentedString(publicMetrics)).append("\n");
    sb.append("    possiblySensitive: ").append(toIndentedString(possiblySensitive)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    nonPublicMetrics: ").append(toIndentedString(nonPublicMetrics)).append("\n");
    sb.append("    promotedMetrics: ").append(toIndentedString(promotedMetrics)).append("\n");
    sb.append("    organicMetrics: ").append(toIndentedString(organicMetrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
