/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Indicates withholding details for [withheld content](https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country).
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class TweetWithheld {
  @JsonProperty("copyright")
  private Boolean copyright = null;

  @JsonProperty("country_codes")
  private List<String> countryCodes = new ArrayList<>();

  /**
   * Indicates whether the content being withheld is the &#x60;tweet&#x60; or a &#x60;user&#x60;.
   */
  public enum ScopeEnum {
    TWEET("tweet"),
    USER("user");

    private String value;

    ScopeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ScopeEnum fromValue(String text) {
      for (ScopeEnum b : ScopeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("scope")
  private ScopeEnum scope = null;

  public TweetWithheld copyright(Boolean copyright) {
    this.copyright = copyright;
    return this;
  }

   /**
   * Indicates if the content is being withheld for on the basis of copyright infringement.
   * @return copyright
  **/
  public Boolean isCopyright() {
    return copyright;
  }

  public void setCopyright(Boolean copyright) {
    this.copyright = copyright;
  }

  public TweetWithheld countryCodes(List<String> countryCodes) {
    this.countryCodes = countryCodes;
    return this;
  }

  public TweetWithheld addCountryCodesItem(String countryCodesItem) {
    this.countryCodes.add(countryCodesItem);
    return this;
  }

   /**
   * Provides a list of countries where this content is not available.
   * @return countryCodes
  **/
  public List<String> getCountryCodes() {
    return countryCodes;
  }

  public void setCountryCodes(List<String> countryCodes) {
    this.countryCodes = countryCodes;
  }

  public TweetWithheld scope(ScopeEnum scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Indicates whether the content being withheld is the &#x60;tweet&#x60; or a &#x60;user&#x60;.
   * @return scope
  **/
  public ScopeEnum getScope() {
    return scope;
  }

  public void setScope(ScopeEnum scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TweetWithheld tweetWithheld = (TweetWithheld) o;
    return Objects.equals(this.copyright, tweetWithheld.copyright) &&
        Objects.equals(this.countryCodes, tweetWithheld.countryCodes) &&
        Objects.equals(this.scope, tweetWithheld.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(copyright, countryCodes, scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TweetWithheld {\n");
    
    sb.append("    copyright: ").append(toIndentedString(copyright)).append("\n");
    sb.append("    countryCodes: ").append(toIndentedString(countryCodes)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
