/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Engagement metrics for the Tweet at the time of the request.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class TweetPublicMetrics {
  @JsonProperty("retweet_count")
  private Integer retweetCount = null;

  @JsonProperty("reply_count")
  private Integer replyCount = null;

  @JsonProperty("like_count")
  private Integer likeCount = null;

  @JsonProperty("quote_count")
  private Integer quoteCount = null;

  public TweetPublicMetrics retweetCount(Integer retweetCount) {
    this.retweetCount = retweetCount;
    return this;
  }

   /**
   * Number of times this Tweet has been Retweeted.
   * @return retweetCount
  **/
  public Integer getRetweetCount() {
    return retweetCount;
  }

  public void setRetweetCount(Integer retweetCount) {
    this.retweetCount = retweetCount;
  }

  public TweetPublicMetrics replyCount(Integer replyCount) {
    this.replyCount = replyCount;
    return this;
  }

   /**
   * Number of times this Tweet has been replied to.
   * @return replyCount
  **/
  public Integer getReplyCount() {
    return replyCount;
  }

  public void setReplyCount(Integer replyCount) {
    this.replyCount = replyCount;
  }

  public TweetPublicMetrics likeCount(Integer likeCount) {
    this.likeCount = likeCount;
    return this;
  }

   /**
   * Number of times this Tweet has been liked.
   * @return likeCount
  **/
  public Integer getLikeCount() {
    return likeCount;
  }

  public void setLikeCount(Integer likeCount) {
    this.likeCount = likeCount;
  }

  public TweetPublicMetrics quoteCount(Integer quoteCount) {
    this.quoteCount = quoteCount;
    return this;
  }

   /**
   * Number of times this Tweet has been quoted.
   * @return quoteCount
  **/
  public Integer getQuoteCount() {
    return quoteCount;
  }

  public void setQuoteCount(Integer quoteCount) {
    this.quoteCount = quoteCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TweetPublicMetrics tweetPublicMetrics = (TweetPublicMetrics) o;
    return Objects.equals(this.retweetCount, tweetPublicMetrics.retweetCount) &&
        Objects.equals(this.replyCount, tweetPublicMetrics.replyCount) &&
        Objects.equals(this.likeCount, tweetPublicMetrics.likeCount) &&
        Objects.equals(this.quoteCount, tweetPublicMetrics.quoteCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(retweetCount, replyCount, likeCount, quoteCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TweetPublicMetrics {\n");
    
    sb.append("    retweetCount: ").append(toIndentedString(retweetCount)).append("\n");
    sb.append("    replyCount: ").append(toIndentedString(replyCount)).append("\n");
    sb.append("    likeCount: ").append(toIndentedString(likeCount)).append("\n");
    sb.append("    quoteCount: ").append(toIndentedString(quoteCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
