/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Specifies the type of attachments (if any) present in this Tweet.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class TweetAttachments {
  @JsonProperty("media_keys")
  private List<String> mediaKeys = null;

  @JsonProperty("poll_ids")
  private List<String> pollIds = null;

  public TweetAttachments mediaKeys(List<String> mediaKeys) {
    this.mediaKeys = mediaKeys;
    return this;
  }

  public TweetAttachments addMediaKeysItem(String mediaKeysItem) {
    if (this.mediaKeys == null) {
      this.mediaKeys = new ArrayList<>();
    }
    this.mediaKeys.add(mediaKeysItem);
    return this;
  }

   /**
   * A list of Media Keys for each one of the media attachments (if media are attached).
   * @return mediaKeys
  **/
  public List<String> getMediaKeys() {
    return mediaKeys;
  }

  public void setMediaKeys(List<String> mediaKeys) {
    this.mediaKeys = mediaKeys;
  }

  public TweetAttachments pollIds(List<String> pollIds) {
    this.pollIds = pollIds;
    return this;
  }

  public TweetAttachments addPollIdsItem(String pollIdsItem) {
    if (this.pollIds == null) {
      this.pollIds = new ArrayList<>();
    }
    this.pollIds.add(pollIdsItem);
    return this;
  }

   /**
   * A list of poll IDs (if polls are attached).
   * @return pollIds
  **/
  public List<String> getPollIds() {
    return pollIds;
  }

  public void setPollIds(List<String> pollIds) {
    this.pollIds = pollIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TweetAttachments tweetAttachments = (TweetAttachments) o;
    return Objects.equals(this.mediaKeys, tweetAttachments.mediaKeys) &&
        Objects.equals(this.pollIds, tweetAttachments.pollIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mediaKeys, pollIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TweetAttachments {\n");
    
    sb.append("    mediaKeys: ").append(toIndentedString(mediaKeys)).append("\n");
    sb.append("    pollIds: ").append(toIndentedString(pollIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
