/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * TweetSearchResponseMeta
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class TweetSearchResponseMeta {
  @JsonProperty("newest_id")
  private String newestId = null;

  @JsonProperty("oldest_id")
  private String oldestId = null;

  @JsonProperty("next_token")
  private String nextToken = null;

  @JsonProperty("result_count")
  private Integer resultCount = null;

  public TweetSearchResponseMeta newestId(String newestId) {
    this.newestId = newestId;
    return this;
  }

   /**
   * Most recent Tweet Id returned by search query
   * @return newestId
  **/
  public String getNewestId() {
    return newestId;
  }

  public void setNewestId(String newestId) {
    this.newestId = newestId;
  }

  public TweetSearchResponseMeta oldestId(String oldestId) {
    this.oldestId = oldestId;
    return this;
  }

   /**
   * Oldest Tweet Id returned by search query
   * @return oldestId
  **/
  public String getOldestId() {
    return oldestId;
  }

  public void setOldestId(String oldestId) {
    this.oldestId = oldestId;
  }

  public TweetSearchResponseMeta nextToken(String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

   /**
   * This value is used to get the next &#x27;page&#x27; of results by providing it to the next_token parameter.
   * @return nextToken
  **/
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(String nextToken) {
    this.nextToken = nextToken;
  }

  public TweetSearchResponseMeta resultCount(Integer resultCount) {
    this.resultCount = resultCount;
    return this;
  }

   /**
   * Number of search query results
   * @return resultCount
  **/
  public Integer getResultCount() {
    return resultCount;
  }

  public void setResultCount(Integer resultCount) {
    this.resultCount = resultCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TweetSearchResponseMeta tweetSearchResponseMeta = (TweetSearchResponseMeta) o;
    return Objects.equals(this.newestId, tweetSearchResponseMeta.newestId) &&
        Objects.equals(this.oldestId, tweetSearchResponseMeta.oldestId) &&
        Objects.equals(this.nextToken, tweetSearchResponseMeta.nextToken) &&
        Objects.equals(this.resultCount, tweetSearchResponseMeta.resultCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newestId, oldestId, nextToken, resultCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TweetSearchResponseMeta {\n");
    
    sb.append("    newestId: ").append(toIndentedString(newestId)).append("\n");
    sb.append("    oldestId: ").append(toIndentedString(oldestId)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    resultCount: ").append(toIndentedString(resultCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
