/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Promoted nonpublic engagement metrics for the Tweet at the time of the request.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class TweetPromotedMetrics {
  @JsonProperty("impression_count")
  private Integer impressionCount = null;

  @JsonProperty("like_count")
  private Integer likeCount = null;

  @JsonProperty("reply_count")
  private Integer replyCount = null;

  @JsonProperty("retweet_count")
  private Integer retweetCount = null;

  public TweetPromotedMetrics impressionCount(Integer impressionCount) {
    this.impressionCount = impressionCount;
    return this;
  }

   /**
   * Number of times this Tweet has been viewed.
   * @return impressionCount
  **/
  public Integer getImpressionCount() {
    return impressionCount;
  }

  public void setImpressionCount(Integer impressionCount) {
    this.impressionCount = impressionCount;
  }

  public TweetPromotedMetrics likeCount(Integer likeCount) {
    this.likeCount = likeCount;
    return this;
  }

   /**
   * Number of times this Tweet has been liked.
   * @return likeCount
  **/
  public Integer getLikeCount() {
    return likeCount;
  }

  public void setLikeCount(Integer likeCount) {
    this.likeCount = likeCount;
  }

  public TweetPromotedMetrics replyCount(Integer replyCount) {
    this.replyCount = replyCount;
    return this;
  }

   /**
   * Number of times this Tweet has been replied to.
   * @return replyCount
  **/
  public Integer getReplyCount() {
    return replyCount;
  }

  public void setReplyCount(Integer replyCount) {
    this.replyCount = replyCount;
  }

  public TweetPromotedMetrics retweetCount(Integer retweetCount) {
    this.retweetCount = retweetCount;
    return this;
  }

   /**
   * Number of times this Tweet has been Retweeted.
   * @return retweetCount
  **/
  public Integer getRetweetCount() {
    return retweetCount;
  }

  public void setRetweetCount(Integer retweetCount) {
    this.retweetCount = retweetCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TweetPromotedMetrics tweetPromotedMetrics = (TweetPromotedMetrics) o;
    return Objects.equals(this.impressionCount, tweetPromotedMetrics.impressionCount) &&
        Objects.equals(this.likeCount, tweetPromotedMetrics.likeCount) &&
        Objects.equals(this.replyCount, tweetPromotedMetrics.replyCount) &&
        Objects.equals(this.retweetCount, tweetPromotedMetrics.retweetCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(impressionCount, likeCount, replyCount, retweetCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TweetPromotedMetrics {\n");
    
    sb.append("    impressionCount: ").append(toIndentedString(impressionCount)).append("\n");
    sb.append("    likeCount: ").append(toIndentedString(likeCount)).append("\n");
    sb.append("    replyCount: ").append(toIndentedString(replyCount)).append("\n");
    sb.append("    retweetCount: ").append(toIndentedString(retweetCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
