/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.EntityIndicesInclusiveExclusive;
import com.twitter.api.client.URLFields;
import com.twitter.api.client.URLImage;

import java.util.ArrayList;
import java.util.List;
/**
 * Represent the portion of text recognized as a URL, and its start and end position within the text.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class UrlEntity extends EntityIndicesInclusiveExclusive {
  @JsonProperty("url")
  private String url = null;

  @JsonProperty("expanded_url")
  private String expandedUrl = null;

  @JsonProperty("display_url")
  private String displayUrl = null;

  @JsonProperty("unwound_url")
  private String unwoundUrl = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("images")
  private List<URLImage> images = null;

  public UrlEntity url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public UrlEntity expandedUrl(String expandedUrl) {
    this.expandedUrl = expandedUrl;
    return this;
  }

   /**
   * Get expandedUrl
   * @return expandedUrl
  **/
  public String getExpandedUrl() {
    return expandedUrl;
  }

  public void setExpandedUrl(String expandedUrl) {
    this.expandedUrl = expandedUrl;
  }

  public UrlEntity displayUrl(String displayUrl) {
    this.displayUrl = displayUrl;
    return this;
  }

   /**
   * The URL as displayed in the Twitter client.
   * @return displayUrl
  **/
  public String getDisplayUrl() {
    return displayUrl;
  }

  public void setDisplayUrl(String displayUrl) {
    this.displayUrl = displayUrl;
  }

  public UrlEntity unwoundUrl(String unwoundUrl) {
    this.unwoundUrl = unwoundUrl;
    return this;
  }

   /**
   * Fully resolved url
   * @return unwoundUrl
  **/
  public String getUnwoundUrl() {
    return unwoundUrl;
  }

  public void setUnwoundUrl(String unwoundUrl) {
    this.unwoundUrl = unwoundUrl;
  }

  public UrlEntity status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public UrlEntity title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the page the URL points to.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public UrlEntity description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the URL landing page.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UrlEntity images(List<URLImage> images) {
    this.images = images;
    return this;
  }

  public UrlEntity addImagesItem(URLImage imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  public List<URLImage> getImages() {
    return images;
  }

  public void setImages(List<URLImage> images) {
    this.images = images;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UrlEntity urlEntity = (UrlEntity) o;
    return Objects.equals(this.url, urlEntity.url) &&
        Objects.equals(this.expandedUrl, urlEntity.expandedUrl) &&
        Objects.equals(this.displayUrl, urlEntity.displayUrl) &&
        Objects.equals(this.unwoundUrl, urlEntity.unwoundUrl) &&
        Objects.equals(this.status, urlEntity.status) &&
        Objects.equals(this.title, urlEntity.title) &&
        Objects.equals(this.description, urlEntity.description) &&
        Objects.equals(this.images, urlEntity.images) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, expandedUrl, displayUrl, unwoundUrl, status, title, description, images, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UrlEntity {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    expandedUrl: ").append(toIndentedString(expandedUrl)).append("\n");
    sb.append("    displayUrl: ").append(toIndentedString(displayUrl)).append("\n");
    sb.append("    unwoundUrl: ").append(toIndentedString(unwoundUrl)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
