/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A list of metrics for this user
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class UserPublicMetrics {
  @JsonProperty("followers_count")
  private Integer followersCount = null;

  @JsonProperty("following_count")
  private Integer followingCount = null;

  @JsonProperty("tweet_count")
  private Integer tweetCount = null;

  @JsonProperty("listed_count")
  private Integer listedCount = null;

  public UserPublicMetrics followersCount(Integer followersCount) {
    this.followersCount = followersCount;
    return this;
  }

   /**
   * Number of users who are following this user.
   * @return followersCount
  **/
  public Integer getFollowersCount() {
    return followersCount;
  }

  public void setFollowersCount(Integer followersCount) {
    this.followersCount = followersCount;
  }

  public UserPublicMetrics followingCount(Integer followingCount) {
    this.followingCount = followingCount;
    return this;
  }

   /**
   * Number of users this user is following.
   * @return followingCount
  **/
  public Integer getFollowingCount() {
    return followingCount;
  }

  public void setFollowingCount(Integer followingCount) {
    this.followingCount = followingCount;
  }

  public UserPublicMetrics tweetCount(Integer tweetCount) {
    this.tweetCount = tweetCount;
    return this;
  }

   /**
   * The number of Tweets (including Retweets) posted by this user.
   * @return tweetCount
  **/
  public Integer getTweetCount() {
    return tweetCount;
  }

  public void setTweetCount(Integer tweetCount) {
    this.tweetCount = tweetCount;
  }

  public UserPublicMetrics listedCount(Integer listedCount) {
    this.listedCount = listedCount;
    return this;
  }

   /**
   * The number of lists that include this user.
   * @return listedCount
  **/
  public Integer getListedCount() {
    return listedCount;
  }

  public void setListedCount(Integer listedCount) {
    this.listedCount = listedCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserPublicMetrics userPublicMetrics = (UserPublicMetrics) o;
    return Objects.equals(this.followersCount, userPublicMetrics.followersCount) &&
        Objects.equals(this.followingCount, userPublicMetrics.followingCount) &&
        Objects.equals(this.tweetCount, userPublicMetrics.tweetCount) &&
        Objects.equals(this.listedCount, userPublicMetrics.listedCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(followersCount, followingCount, tweetCount, listedCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPublicMetrics {\n");
    
    sb.append("    followersCount: ").append(toIndentedString(followersCount)).append("\n");
    sb.append("    followingCount: ").append(toIndentedString(followingCount)).append("\n");
    sb.append("    tweetCount: ").append(toIndentedString(tweetCount)).append("\n");
    sb.append("    listedCount: ").append(toIndentedString(listedCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
