/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UsersFollowingCreateResponseData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class UsersFollowingCreateResponseData {
  @JsonProperty("following")
  private Boolean following = null;

  @JsonProperty("pending_follow")
  private Boolean pendingFollow = null;

  public UsersFollowingCreateResponseData following(Boolean following) {
    this.following = following;
    return this;
  }

   /**
   * Get following
   * @return following
  **/
  public Boolean isFollowing() {
    return following;
  }

  public void setFollowing(Boolean following) {
    this.following = following;
  }

  public UsersFollowingCreateResponseData pendingFollow(Boolean pendingFollow) {
    this.pendingFollow = pendingFollow;
    return this;
  }

   /**
   * Get pendingFollow
   * @return pendingFollow
  **/
  public Boolean isPendingFollow() {
    return pendingFollow;
  }

  public void setPendingFollow(Boolean pendingFollow) {
    this.pendingFollow = pendingFollow;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersFollowingCreateResponseData usersFollowingCreateResponseData = (UsersFollowingCreateResponseData) o;
    return Objects.equals(this.following, usersFollowingCreateResponseData.following) &&
        Objects.equals(this.pendingFollow, usersFollowingCreateResponseData.pendingFollow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(following, pendingFollow);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersFollowingCreateResponseData {\n");
    
    sb.append("    following: ").append(toIndentedString(following)).append("\n");
    sb.append("    pendingFollow: ").append(toIndentedString(pendingFollow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
