/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.UserEntities;
import com.twitter.api.client.UserPublicMetrics;
import com.twitter.api.client.UserWithheld;

import java.time.OffsetDateTime;
/**
 * The Twitter User object
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class User {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("created_at")
  private OffsetDateTime createdAt = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("protected")
  private Boolean _protected = null;

  @JsonProperty("verified")
  private Boolean verified = null;

  @JsonProperty("withheld")
  private UserWithheld withheld = null;

  @JsonProperty("profile_image_url")
  private String profileImageUrl = null;

  @JsonProperty("location")
  private String location = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("entities")
  private UserEntities entities = null;

  @JsonProperty("pinned_tweet_id")
  private String pinnedTweetId = null;

  @JsonProperty("public_metrics")
  private UserPublicMetrics publicMetrics = null;

  public User id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public User createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Creation time of this user.
   * @return createdAt
  **/
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public User name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The friendly name of this user, as shown on their profile.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public User username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public User _protected(Boolean _protected) {
    this._protected = _protected;
    return this;
  }

   /**
   * Indicates if this user has chosen to protect their Tweets (in other words, if this user&#x27;s Tweets are private).
   * @return _protected
  **/
  public Boolean isProtected() {
    return _protected;
  }

  public void setProtected(Boolean _protected) {
    this._protected = _protected;
  }

  public User verified(Boolean verified) {
    this.verified = verified;
    return this;
  }

   /**
   * Indicate if this user is a verified Twitter User.
   * @return verified
  **/
  public Boolean isVerified() {
    return verified;
  }

  public void setVerified(Boolean verified) {
    this.verified = verified;
  }

  public User withheld(UserWithheld withheld) {
    this.withheld = withheld;
    return this;
  }

   /**
   * Get withheld
   * @return withheld
  **/
  public UserWithheld getWithheld() {
    return withheld;
  }

  public void setWithheld(UserWithheld withheld) {
    this.withheld = withheld;
  }

  public User profileImageUrl(String profileImageUrl) {
    this.profileImageUrl = profileImageUrl;
    return this;
  }

   /**
   * The URL to the profile image for this user.
   * @return profileImageUrl
  **/
  public String getProfileImageUrl() {
    return profileImageUrl;
  }

  public void setProfileImageUrl(String profileImageUrl) {
    this.profileImageUrl = profileImageUrl;
  }

  public User location(String location) {
    this.location = location;
    return this;
  }

   /**
   * The location specified in the user&#x27;s profile, if the user provided one. As this is a freeform value, it may not indicate a valid location, but it may be fuzzily evaluated when performing searches with location queries.
   * @return location
  **/
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public User url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL specified in the user&#x27;s profile.
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public User description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The text of this user&#x27;s profile description (also known as bio), if the user provided one.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public User entities(UserEntities entities) {
    this.entities = entities;
    return this;
  }

   /**
   * Get entities
   * @return entities
  **/
  public UserEntities getEntities() {
    return entities;
  }

  public void setEntities(UserEntities entities) {
    this.entities = entities;
  }

  public User pinnedTweetId(String pinnedTweetId) {
    this.pinnedTweetId = pinnedTweetId;
    return this;
  }

   /**
   * Get pinnedTweetId
   * @return pinnedTweetId
  **/
  public String getPinnedTweetId() {
    return pinnedTweetId;
  }

  public void setPinnedTweetId(String pinnedTweetId) {
    this.pinnedTweetId = pinnedTweetId;
  }

  public User publicMetrics(UserPublicMetrics publicMetrics) {
    this.publicMetrics = publicMetrics;
    return this;
  }

   /**
   * Get publicMetrics
   * @return publicMetrics
  **/
  public UserPublicMetrics getPublicMetrics() {
    return publicMetrics;
  }

  public void setPublicMetrics(UserPublicMetrics publicMetrics) {
    this.publicMetrics = publicMetrics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.id, user.id) &&
        Objects.equals(this.createdAt, user.createdAt) &&
        Objects.equals(this.name, user.name) &&
        Objects.equals(this.username, user.username) &&
        Objects.equals(this._protected, user._protected) &&
        Objects.equals(this.verified, user.verified) &&
        Objects.equals(this.withheld, user.withheld) &&
        Objects.equals(this.profileImageUrl, user.profileImageUrl) &&
        Objects.equals(this.location, user.location) &&
        Objects.equals(this.url, user.url) &&
        Objects.equals(this.description, user.description) &&
        Objects.equals(this.entities, user.entities) &&
        Objects.equals(this.pinnedTweetId, user.pinnedTweetId) &&
        Objects.equals(this.publicMetrics, user.publicMetrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, name, username, _protected, verified, withheld, profileImageUrl, location, url, description, entities, pinnedTweetId, publicMetrics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    _protected: ").append(toIndentedString(_protected)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    withheld: ").append(toIndentedString(withheld)).append("\n");
    sb.append("    profileImageUrl: ").append(toIndentedString(profileImageUrl)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    pinnedTweetId: ").append(toIndentedString(pinnedTweetId)).append("\n");
    sb.append("    publicMetrics: ").append(toIndentedString(publicMetrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
