/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UsersLikesCreateResponseData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class UsersLikesCreateResponseData {
  @JsonProperty("liked")
  private Boolean liked = null;

  public UsersLikesCreateResponseData liked(Boolean liked) {
    this.liked = liked;
    return this;
  }

   /**
   * Get liked
   * @return liked
  **/
  public Boolean isLiked() {
    return liked;
  }

  public void setLiked(Boolean liked) {
    this.liked = liked;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersLikesCreateResponseData usersLikesCreateResponseData = (UsersLikesCreateResponseData) o;
    return Objects.equals(this.liked, usersLikesCreateResponseData.liked);
  }

  @Override
  public int hashCode() {
    return Objects.hash(liked);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersLikesCreateResponseData {\n");
    
    sb.append("    liked: ").append(toIndentedString(liked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
