/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.UrlEntity;

import java.util.ArrayList;
import java.util.List;
/**
 * Expanded details for the URL specified in the user&#x27;s profile, with start and end indices.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class UserEntitiesUrl {
  @JsonProperty("urls")
  private List<UrlEntity> urls = null;

  public UserEntitiesUrl urls(List<UrlEntity> urls) {
    this.urls = urls;
    return this;
  }

  public UserEntitiesUrl addUrlsItem(UrlEntity urlsItem) {
    if (this.urls == null) {
      this.urls = new ArrayList<>();
    }
    this.urls.add(urlsItem);
    return this;
  }

   /**
   * Get urls
   * @return urls
  **/
  public List<UrlEntity> getUrls() {
    return urls;
  }

  public void setUrls(List<UrlEntity> urls) {
    this.urls = urls;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserEntitiesUrl userEntitiesUrl = (UserEntitiesUrl) o;
    return Objects.equals(this.urls, userEntitiesUrl.urls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(urls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserEntitiesUrl {\n");
    
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
