/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.Problem;
import com.twitter.api.client.UsersLikesCreateResponseData;

import java.util.ArrayList;
import java.util.List;
/**
 * UsersLikesDeleteResponse
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class UsersLikesDeleteResponse {
  @JsonProperty("data")
  private UsersLikesCreateResponseData data = null;

  @JsonProperty("errors")
  private List<Problem> errors = null;

  public UsersLikesDeleteResponse data(UsersLikesCreateResponseData data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  public UsersLikesCreateResponseData getData() {
    return data;
  }

  public void setData(UsersLikesCreateResponseData data) {
    this.data = data;
  }

  public UsersLikesDeleteResponse errors(List<Problem> errors) {
    this.errors = errors;
    return this;
  }

  public UsersLikesDeleteResponse addErrorsItem(Problem errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  public List<Problem> getErrors() {
    return errors;
  }

  public void setErrors(List<Problem> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersLikesDeleteResponse usersLikesDeleteResponse = (UsersLikesDeleteResponse) o;
    return Objects.equals(this.data, usersLikesDeleteResponse.data) &&
        Objects.equals(this.errors, usersLikesDeleteResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersLikesDeleteResponse {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
