/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Nonpublic engagement metrics for the Media at the time of the request.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class VideoNonPublicMetrics {
  @JsonProperty("playback_0_count")
  private Integer playback0Count = null;

  @JsonProperty("playback_25_count")
  private Integer playback25Count = null;

  @JsonProperty("playback_50_count")
  private Integer playback50Count = null;

  @JsonProperty("playback_75_count")
  private Integer playback75Count = null;

  @JsonProperty("playback_100_count")
  private Integer playback100Count = null;

  public VideoNonPublicMetrics playback0Count(Integer playback0Count) {
    this.playback0Count = playback0Count;
    return this;
  }

   /**
   * Number of users who made it through 0% of the video.
   * @return playback0Count
  **/
  public Integer getPlayback0Count() {
    return playback0Count;
  }

  public void setPlayback0Count(Integer playback0Count) {
    this.playback0Count = playback0Count;
  }

  public VideoNonPublicMetrics playback25Count(Integer playback25Count) {
    this.playback25Count = playback25Count;
    return this;
  }

   /**
   * Number of users who made it through 25% of the video.
   * @return playback25Count
  **/
  public Integer getPlayback25Count() {
    return playback25Count;
  }

  public void setPlayback25Count(Integer playback25Count) {
    this.playback25Count = playback25Count;
  }

  public VideoNonPublicMetrics playback50Count(Integer playback50Count) {
    this.playback50Count = playback50Count;
    return this;
  }

   /**
   * Number of users who made it through 50% of the video.
   * @return playback50Count
  **/
  public Integer getPlayback50Count() {
    return playback50Count;
  }

  public void setPlayback50Count(Integer playback50Count) {
    this.playback50Count = playback50Count;
  }

  public VideoNonPublicMetrics playback75Count(Integer playback75Count) {
    this.playback75Count = playback75Count;
    return this;
  }

   /**
   * Number of users who made it through 75% of the video.
   * @return playback75Count
  **/
  public Integer getPlayback75Count() {
    return playback75Count;
  }

  public void setPlayback75Count(Integer playback75Count) {
    this.playback75Count = playback75Count;
  }

  public VideoNonPublicMetrics playback100Count(Integer playback100Count) {
    this.playback100Count = playback100Count;
    return this;
  }

   /**
   * Number of users who made it through 100% of the video.
   * @return playback100Count
  **/
  public Integer getPlayback100Count() {
    return playback100Count;
  }

  public void setPlayback100Count(Integer playback100Count) {
    this.playback100Count = playback100Count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoNonPublicMetrics videoNonPublicMetrics = (VideoNonPublicMetrics) o;
    return Objects.equals(this.playback0Count, videoNonPublicMetrics.playback0Count) &&
        Objects.equals(this.playback25Count, videoNonPublicMetrics.playback25Count) &&
        Objects.equals(this.playback50Count, videoNonPublicMetrics.playback50Count) &&
        Objects.equals(this.playback75Count, videoNonPublicMetrics.playback75Count) &&
        Objects.equals(this.playback100Count, videoNonPublicMetrics.playback100Count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playback0Count, playback25Count, playback50Count, playback75Count, playback100Count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoNonPublicMetrics {\n");
    
    sb.append("    playback0Count: ").append(toIndentedString(playback0Count)).append("\n");
    sb.append("    playback25Count: ").append(toIndentedString(playback25Count)).append("\n");
    sb.append("    playback50Count: ").append(toIndentedString(playback50Count)).append("\n");
    sb.append("    playback75Count: ").append(toIndentedString(playback75Count)).append("\n");
    sb.append("    playback100Count: ").append(toIndentedString(playback100Count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
