/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * OpenAPI spec version: 2.31
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.twitter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.twitter.api.client.CommonMediaFields;
import com.twitter.api.client.VideoNonPublicMetrics;
import com.twitter.api.client.VideoOrganicMetrics;
import com.twitter.api.client.VideoPromotedMetrics;
import com.twitter.api.client.VideoPublicMetrics;

/**
 * Video
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-03T13:24:26.911240+01:00[Europe/Zurich]")
public class Video extends CommonMediaFields implements OneOfMedia {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    VIDEO("video");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("preview_image_url")
  private String previewImageUrl = null;

  @JsonProperty("duration_ms")
  private Integer durationMs = null;

  @JsonProperty("public_metrics")
  private VideoPublicMetrics publicMetrics = null;

  @JsonProperty("non_public_metrics")
  private VideoNonPublicMetrics nonPublicMetrics = null;

  @JsonProperty("organic_metrics")
  private VideoOrganicMetrics organicMetrics = null;

  @JsonProperty("promoted_metrics")
  private VideoPromotedMetrics promotedMetrics = null;

  public Video type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public Video previewImageUrl(String previewImageUrl) {
    this.previewImageUrl = previewImageUrl;
    return this;
  }

   /**
   * Get previewImageUrl
   * @return previewImageUrl
  **/
  public String getPreviewImageUrl() {
    return previewImageUrl;
  }

  public void setPreviewImageUrl(String previewImageUrl) {
    this.previewImageUrl = previewImageUrl;
  }

  public Video durationMs(Integer durationMs) {
    this.durationMs = durationMs;
    return this;
  }

   /**
   * Get durationMs
   * @return durationMs
  **/
  public Integer getDurationMs() {
    return durationMs;
  }

  public void setDurationMs(Integer durationMs) {
    this.durationMs = durationMs;
  }

  public Video publicMetrics(VideoPublicMetrics publicMetrics) {
    this.publicMetrics = publicMetrics;
    return this;
  }

   /**
   * Get publicMetrics
   * @return publicMetrics
  **/
  public VideoPublicMetrics getPublicMetrics() {
    return publicMetrics;
  }

  public void setPublicMetrics(VideoPublicMetrics publicMetrics) {
    this.publicMetrics = publicMetrics;
  }

  public Video nonPublicMetrics(VideoNonPublicMetrics nonPublicMetrics) {
    this.nonPublicMetrics = nonPublicMetrics;
    return this;
  }

   /**
   * Get nonPublicMetrics
   * @return nonPublicMetrics
  **/
  public VideoNonPublicMetrics getNonPublicMetrics() {
    return nonPublicMetrics;
  }

  public void setNonPublicMetrics(VideoNonPublicMetrics nonPublicMetrics) {
    this.nonPublicMetrics = nonPublicMetrics;
  }

  public Video organicMetrics(VideoOrganicMetrics organicMetrics) {
    this.organicMetrics = organicMetrics;
    return this;
  }

   /**
   * Get organicMetrics
   * @return organicMetrics
  **/
  public VideoOrganicMetrics getOrganicMetrics() {
    return organicMetrics;
  }

  public void setOrganicMetrics(VideoOrganicMetrics organicMetrics) {
    this.organicMetrics = organicMetrics;
  }

  public Video promotedMetrics(VideoPromotedMetrics promotedMetrics) {
    this.promotedMetrics = promotedMetrics;
    return this;
  }

   /**
   * Get promotedMetrics
   * @return promotedMetrics
  **/
  public VideoPromotedMetrics getPromotedMetrics() {
    return promotedMetrics;
  }

  public void setPromotedMetrics(VideoPromotedMetrics promotedMetrics) {
    this.promotedMetrics = promotedMetrics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Video video = (Video) o;
    return Objects.equals(this.type, video.type) &&
        Objects.equals(this.previewImageUrl, video.previewImageUrl) &&
        Objects.equals(this.durationMs, video.durationMs) &&
        Objects.equals(this.publicMetrics, video.publicMetrics) &&
        Objects.equals(this.nonPublicMetrics, video.nonPublicMetrics) &&
        Objects.equals(this.organicMetrics, video.organicMetrics) &&
        Objects.equals(this.promotedMetrics, video.promotedMetrics) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, previewImageUrl, durationMs, publicMetrics, nonPublicMetrics, organicMetrics, promotedMetrics, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Video {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    previewImageUrl: ").append(toIndentedString(previewImageUrl)).append("\n");
    sb.append("    durationMs: ").append(toIndentedString(durationMs)).append("\n");
    sb.append("    publicMetrics: ").append(toIndentedString(publicMetrics)).append("\n");
    sb.append("    nonPublicMetrics: ").append(toIndentedString(nonPublicMetrics)).append("\n");
    sb.append("    organicMetrics: ").append(toIndentedString(organicMetrics)).append("\n");
    sb.append("    promotedMetrics: ").append(toIndentedString(promotedMetrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
