# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.1.0/variables.json
Variables:
  XConnector:
    # Url to x connector
    Url: https://api.twitter.com
    # Key to connect to the X Account
    Key: ""
    # SecretKey to connect to the X Account
    #[password]
    SecretKey: ${decrypt:}
