name: E2E-Build

on:
  schedule:
    - cron:  '0 1 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    secrets:
      mvnArgs: -Dx.url=${{secrets.URL}} -Dx.key=${{secrets.KEY}} -Dx.secretKey=${{secrets.SECRET_KEY}} -DtestEnvironment=E2E