name: CI-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    secrets:
      mvnArgs: -Dx.url=${{secrets.URL}} -Dx.key=${{secrets.KEY}} -Dx.secretKey=${{secrets.SECRET_KEY}} "-DtestEnvironment=${{ secrets.END_2_END_TESTING_ENV }}"